### ISSUE TITLE
name 'Job' is not defined

### ISSUE THREAD

**Issue by shiertier** [agentd00nut/midjourney-graph#3]
I am not good at Python, and only know some basic operations. 
Therefore, my question may seem very simple, but it is really bothering me and I cannot solve it on my own.
I followed the installation steps in the readme, installed the dependencies first, and then ran [python main.py]. 
However, an error was returned saying [name 'Job' is not defined].

```
Traceback (most recent call last):
  File "C:\git\midjourney-graph\main.py", line 5, in <module>
    from src.callbacks.runJob import runJob
  File "C:\git\midjourney-graph\src\callbacks\runJob.py", line 9, in <module>
    from src.discord import DiscordLink
  File "C:\git\midjourney-graph\src\discord.py", line 3, in <module>
    from src.node import Node
  File "C:\git\midjourney-graph\src\node.py", line 16, in <module>
    class Node:
  File "C:\git\midjourney-graph\src\node.py", line 27, in Node
    job: Job = None
NameError: name 'Job' is not defined
```

I hope to receive your answer. Thank you very much.

**Comment by shiertier** [comment]
I resolved the issue by using an internet-connected chatbot, ChatGPT. 

The problem was that I received an error report of "name 'Job' is not defined" when I ran the project at https://github.com/agentd00nut/midjourney-graph. 

The solution was as follows:

This error typically means that a name (in this case, Job) is not defined. The method of resolving this issue depends on which module or class defines Job, as you need to import it to use it.

After browsing the code repository of this project, I found that a class named Job is defined in the job.py file. This class is imported into a Python module such as main.py or somewhere else. However, if it is not properly imported, an error report of "name 'Job' is not defined" will appear.

Therefore, in your code, make sure that the Job class is correctly imported. You can try to import it with the following statement:

`from job import Job`

If you have already imported the class and still receive this error, you may need to check the position and scope of the import statements to ensure they are visible in the code where Job is used.



Then I processed it like this:
Add "from src.job import Job" to node.py
